import { Response } from "express";
import { prisma } from "../config/db";
import { AuthenticatedRequest } from "../middlewares/roleGuard";
import { createNotification } from "../utils/notificationService";

export const generatePayroll = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { userId, month, baseSalary, bonus, deductions } = req.body;

    if (req.user!.role !== "HR") {
      return res.status(403).json({ error: "Forbidden: Only HR administrators can generate payroll." });
    }

    if (!userId || !month || baseSalary === undefined) {
      return res.status(400).json({ error: "User ID, month (YYYY-MM), and base salary are required." });
    }

    // Validate month format (YYYY-MM)
    if (!/^\d{4}-\d{2}$/.test(month)) {
      return res.status(400).json({ error: "Invalid month format. Please use YYYY-MM." });
    }

    const baseVal = parseFloat(baseSalary);
    const bonusVal = parseFloat(bonus || 0);
    const dedVal = parseFloat(deductions || 0);

    if (isNaN(baseVal) || isNaN(bonusVal) || isNaN(dedVal)) {
      return res.status(400).json({ error: "Salary values must be numbers." });
    }

    const employee = await prisma.user.findUnique({
      where: { id: userId }
    });

    if (!employee) {
      return res.status(404).json({ error: "Employee not found." });
    }

    // Check if payroll already exists
    const existing = await prisma.payroll.findUnique({
      where: {
        userId_month: {
          userId,
          month
        }
      }
    });

    if (existing) {
      return res.status(400).json({ error: "Payroll for this employee and month already exists." });
    }

    const netSalary = baseVal + bonusVal - dedVal;

    const payroll = await prisma.payroll.create({
      data: {
        userId,
        month,
        baseSalary: baseVal,
        bonus: bonusVal,
        deductions: dedVal,
        netSalary,
        status: "PENDING"
      },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true,
            role: true
          }
        }
      }
    });

    // Notify employee of generated payslip
    await createNotification(
      userId,
      "Salary Statement Generated",
      `Your payroll statement for ${month} ($${netSalary.toFixed(2)}) has been generated by HR.`,
      "PAYROLL",
      "/dashboard/payroll"
    );

    return res.status(201).json({ message: "Payroll entry generated successfully.", payroll });
  } catch (err) {
    console.error("Generate Payroll Error:", err);
    return res.status(500).json({ error: "Internal server error." });
  }
};

export const getPayrollLedger = async (req: AuthenticatedRequest, res: Response) => {
  try {
    let payrolls = [];

    if (req.user!.role === "HR") {
      // HR sees all payroll records
      payrolls = await prisma.payroll.findMany({
        orderBy: { month: "desc" },
        include: {
          user: {
            select: {
              id: true,
              name: true,
              email: true,
              role: true
            }
          }
        }
      });
    } else {
      // Employees see only their own payroll records
      payrolls = await prisma.payroll.findMany({
        where: {
          userId: req.user!.id
        },
        orderBy: { month: "desc" },
        include: {
          user: {
            select: {
              id: true,
              name: true,
              email: true,
              role: true
            }
          }
        }
      });
    }

    return res.status(200).json({ payrolls });
  } catch (err) {
    console.error("Fetch Payroll Ledger Error:", err);
    return res.status(500).json({ error: "Internal server error." });
  }
};

export const payPayroll = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const id = req.params.id as string;

    if (req.user!.role !== "HR") {
      return res.status(403).json({ error: "Forbidden: Only HR administrators can mark payroll as paid." });
    }

    const existing = await prisma.payroll.findUnique({
      where: { id }
    });

    if (!existing) {
      return res.status(404).json({ error: "Payroll record not found." });
    }

    if (existing.status === "PAID") {
      return res.status(400).json({ error: "Payroll has already been paid." });
    }

    const updated = await prisma.payroll.update({
      where: { id },
      data: {
        status: "PAID",
        paidAt: new Date()
      },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true
          }
        }
      }
    });

    // Notify employee of payment disbursement
    await createNotification(
      updated.userId,
      "Salary Payment Disbursed",
      `Your salary of $${updated.netSalary.toFixed(2)} for period ${updated.month} has been disbursed and marked as PAID.`,
      "PAYROLL",
      "/dashboard/payroll"
    );

    return res.status(200).json({ message: "Payroll paid successfully.", payroll: updated });
  } catch (err) {
    console.error("Pay Payroll Error:", err);
    return res.status(500).json({ error: "Internal server error." });
  }
};
